### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by staberas** [elect-gombe/k210_mmd#7]
Im getting soon a Maix-bit and im trying to understand how does this code works, 
do you convert the 3d mmd into bmp files and play it as video?
 Thanks!

**Comment by elect-gombe** [comment]
No, this program load mmd model file and texture files and motion file, then place them to ram, and render, and animate, etc..

Everything is done on k210.

Here's release https://github.com/elect-gombe/k210_mmd/releases

**Comment by staberas** [comment]
Thanks, im thinking of making a "Gatebox" like device with Visual/voice recognition do you think this program leaves enough memory to run the rest of the functions?

**Comment by elect-gombe** [comment]
Ah, probably yes.
And this program doesn’t use KPU, which means you can use CPU and kpu simultaneously while rendering.

Most of the memory is used in the model and motion data. This particular release model and motion data use around 3MB. 

You can resize Textures if needed. If you don't use a long dancing motion, you can save memory.

Maybe MaixPy is not suitable because it uses a lot of memory, so a standalone or RTOS project would be nice.

**Comment by elect-gombe** [comment]
Feel free to reopen if you have any questions.
